export enum FilterRule {
  Equal = "eq",
  NotEqual = "ne",
  GreaterThan = "gt",
  GreaterThanOrEqual = "ge",
  LessThan = "lt",
  LessThanOrEqual = "le",
  Contains = "contains",
  NotContains = "not_contains",
  StartsWith = "starts_with",
  EndsWith = "ends_with",
  In = "in",
  NotIn = "not_in",
  Between = "between",
  NotBetween = "not_between",
  IsNull = "is_null",
  IsNotNull = "is_not_null",
  IsEmpty = "is_empty",
  IsNotEmpty = "is_not_empty",
  IsTrue = "is_true",
  IsFalse = "is_false",
}
